---
- hosts: "{{ hosts }}"
  vars:
    db_url: "{{ lookup('env', 'HP_DATABASE_URL') }}"
    db_username: "{{ lookup('env', 'HP_DATABASE_USERNAME') }}"
    db_password: "{{ lookup('env', 'HP_DATABASE_PASSWORD') }}"

  tasks:
  - fail: msg="HP_DATABASE_USERNAME is not defined"
    when: db_username is undefined

  - fail: msg="HP_DATABASE_PASSWORD is not defined"
    when: db_password is undefined
  
  - fail: msg="HP_DATABASE_URL is not defined"
    when: db_url is undefined
      
  - name: Deploy database scripts 
    command: flyway migrate -user="{{ db_username }}"  -url="{{ db_url }}" -password="{{ db_password }}" -configFile="./database/flyway.conf"
